### ISSUE TITLE
Incorrect Query for Updated Question

### ISSUE THREAD

**Issue by BilalSubhani** [lucius-xiao-liu/Leetcode---Database#2]
For [1789. Primary Department for Each Employee](https://leetcode.com/problems/primary-department-for-each-employee/): 

The query is not working for the updated version of this question on LeetCode. I would like to provide an updated version of the solution that clears all the test cases and beats 93% of MS SQL Server users. 

![image](https://github.com/lucius-xiao-liu/Leetcode---Database/assets/139504369/9abd82f8-3faa-4d07-a58b-3ea800fc59bb)

**Comment by BilalSubhani** [comment]
## Solution

WITH EmployeeCounts AS (
    SELECT 
        employee_id,
        COUNT(*) AS count,
        MAX(primary_flag) AS primary_flag
    FROM 
        Employee 
    GROUP BY 
        employee_id
)
SELECT 
    e.employee_id, 
    COALESCE(
        MAX(CASE WHEN e.primary_flag = 'Y' THEN e.department_id ELSE NULL END),
        MIN(CASE WHEN e.primary_flag = 'N' THEN e.department_id ELSE NULL END)
    ) AS department_id 
FROM 
    Employee e
JOIN 
    EmployeeCounts ec ON e.employee_id = ec.employee_id
GROUP BY 
    e.employee_id
HAVING 
    COUNT(CASE WHEN e.primary_flag = 'Y' THEN e.department_id ELSE NULL END) = 1 
    OR COUNT(CASE WHEN e.primary_flag = 'N' THEN e.department_id ELSE NULL END) = 1
    OR 'Y' IN (SELECT primary_flag FROM Employee WHERE employee_id = e.employee_id);

**Comment by lucius-xiao-liu** [comment]
nice work!

**Comment by lucius-xiao-liu** [comment]
> This query is not working for the updated version of this question on LeetCode. I would like to provide an updated version of the solution that clears all the test cases and beats 93% of MS SQL Server users.
> 
> ![image](https://private-user-images.githubusercontent.com/139504369/338799534-9abd82f8-3faa-4d07-a58b-3ea800fc59bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjA0NjksIm5iZiI6MTcxODE2MDE2OSwicGF0aCI6Ii8xMzk1MDQzNjkvMzM4Nzk5NTM0LTlhYmQ4MmY4LTNmYWEtNGQwNy1hNThiLTNlYTgwMGZjNTliYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwMjQyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmVmODNlOWFhY2JhNDIxYjViMjljMmYyM2UxODAzNmU1YjRhNGEyNTJlMGFlY2U2Mzc4YjlmNjI5NzYzNmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-32DLus9KDd7JPQtkoS4_4dF1ktcTdrmnVVyL3Yw5W8)

which script are you referring to? I haven't followed Leetcode for years so I don't know which one needs to be updated. Thanks for the note here and would like to address it and update it for future visitors

**Comment by BilalSubhani** [comment]
I used Ms SQL Server. 

I came to your repo for help, thought I should add the solution here if someone  needs it, since your repo was the top recommendation.

**Comment by lucius-xiao-liu** [comment]
surprisingly. glad it helped, but not helpful based on the change. still confused about which SQL question you are addressing, want to update it.

**Comment by BilalSubhani** [comment]
Yeah, I totally forgot to mention the title of the problem. Its [1789. Primary Department for Each Employee], part of SQL 50, (https://leetcode.com/problems/primary-department-for-each-employee/)

**Comment by lucius-xiao-liu** [comment]
updated and with your credit on the top of the line! Thanks for the message!

**Comment by BilalSubhani** [comment]
Thank you.
